{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes-share.secretName" . }}
  labels:
    {{- include "hermes-share.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.apiKeyKey }}: {{ .Values.auth.managementApiKey | quote }}
{{- end }}
